### ISSUE TITLE
Anomalize Notebook Typo

### ISSUE THREAD

**Issue by AndrewKinsman** [holisticinfosec/toolsmith_R#3]
I very much enjoyed your blog/notebook, thanks Russ. FYI, in the final cell of your anomalize security logs notebook:

security_access_logs %>% 
  filter(server == "SERVER549521")

should read:

security_access_logs %>% 
  filter(server == "SERVER-549521")

i.e. the hyphen is missing. 

Also, IMHO it's generally better practice to link to the data like this:
logs <- read_csv("https://raw.githubusercontent.com/holisticinfosec/toolsmith_R/master/anomalize/log.csv")

instead of "imposing" a working directory on anyone wishing to run the notebook on their local machine.

**Comment by holisticinfosec** [comment]
Andrew, thank you re: typo and best practice. Both corrected.
